  swagger: "2.0"
  info: 
    description: "API to manage customers from a banking perspective"
    version: "1"
    title: "[Sensedia Bank] Customer Service API"
  host: "api-solutions.sensedia.com"
  basePath: "/sandbox/customer-service/v1"
  schemes: 
    - "https"
  paths: 
    /customers/{customerId}: 
      get: 
        summary: "Displays a customer by its id"
        description: "Displays a customer by its id"
        parameters: []
        responses: 
          200: 
            description: "OK"
      put: 
        summary: "Updates a customer"
        description: "Updates a customer"
        parameters: []
        responses: 
          200: 
            description: "OK"
      parameters: 
        - 
          name: "customerId"
          in: "path"
          description: "customerId"
          required: true
          type: "string"
    /customers: 
      get: 
        summary: "Displays all customers"
        description: "Displays all customers"
        parameters: []
        responses: 
          200: 
            description: "OK"
      post: 
        summary: "Creates a new customer"
        description: "Creates a new customer"
        parameters: []
        responses: 
          200: 
            description: "OK"
