swagger: '2.0'
info:
  description: API to manage payments from a banking perspective
  version: '1'
  title: '[Sensedia Bank] Payment Service API'
host: api-solutions.sensedia.com
basePath: /sandbox/payment-service/v1
schemes:
  - https
paths:
  '/payments/{accountId}':
    get:
      summary: Displays payments of a given account
      description: Displays payments of a given account
      parameters: []
      responses:
        '200':
          description: OK
    parameters:
      - name: accountId
        in: path
        description: accountId
        required: true
        type: string
  /payments:
    post:
      summary: Creates a new payment
      description: Creates a new payment
      parameters: []
      responses:
        '200':
          description: OK